### ISSUE TITLE
Revert favicons

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-kickstarter#18]
I still believe we should remove old this bloating boilerplate stuff like the different favicons.

If i am going to setup a new page (kickstart luya project) - i have to create those favicons anyhow by myself with one of those online generators - so people have to remove all those images and values from main layout - so i think this makes just no sense.

@luyadev/coredev thoughts?

**Comment by nadar** [comment]
So i would remove all those lines including all the images, except of faivon.png like it was on 1.0.0 release.

https://github.com/luyadev/luya-kickstarter/blob/master/views/layouts/main.php#L20-L26

**Comment by dev7ch** [comment]
@nadar ok i agree, maybe just put a comment with a link to a favicon generator is a helpful solution

**Comment by nadar** [comment]
Where would you put this info? Not sure if this is necessary. Its basic website know-how, its not luya related.

**Comment by dev7ch** [comment]
e.g. `views/layout/main.php` ( there, where it is needed)

**Comment by nadar** [comment]
Have you seen this in any other boilerplate html templates? 😄 

```
<!--
Put your favicons here ...
-->
```

**Comment by dev7ch** [comment]
no, but where is your pioneer spirit :) 
do as you feel.

**Comment by nadar** [comment]
Less is more!

**Comment by nadar** [comment]
@dev7ch would you please take care of this issue? So we could release 1.0.1

**Comment by dev7ch** [comment]
@nadar sorry i am busy next days, please can you do it, thanks
