### ISSUE TITLE
"view file can not be blank", "json config cannot be blank" while creating layout from admin panel

### ISSUE THREAD

**Issue by igorveremsky** [luyadev/luya-kickstarter#19]
I create project using instruction from https://luya.io/guide/install-windows link , than i test them and trying to add new layout from admin panel and i get this error:

![screenshot_151](https://user-images.githubusercontent.com/13087365/36744176-d0980fb0-1bf4-11e8-9875-4dbc4d8f4210.png)

**Comment by nadar** [comment]
@igorveremsky layouts must be provided trough import command, but yes there should not be an add button indeed :-) 

Read more about layouts: https://luya.io/guide/app-cmslayouts

I am going to make an issue for the "wrong add button".

**Comment by igorveremsky** [comment]
@nadar i also cant do this :) i create 2columns.json:
```json
{
  "rows" : [
    [
      {"cols": 8, "var": "left", "label": "Main content Left"},
      {"cols": 4, "var": "right", "label": "Sidebar Right"}
    ]
  ]
}
```
2columns.php:
```php
<div class="row">
    <div class="col-md-6">
		<?= $placeholders['left']; ?>
    </div>
    <div class="col-md-6">
		<?= $placeholders['right']; ?>
    </div>
</div>
```

at views/cmslayouts folder. Than i run luya import and get:
![screenshot_152](https://user-images.githubusercontent.com/13087365/36780397-923126ee-1c7b-11e8-801d-f4acf2e3c98a.png)
But i dont see it in admin panel:
![screenshot_153](https://user-images.githubusercontent.com/13087365/36780544-f63e4b6c-1c7b-11e8-8745-1bdd0741d0c5.png)

What can be wrong?

**Comment by nadar** [comment]
You have to run the luya bin outside of the vendor folder. On windows its best way to use php index.php import in the public_html folder.

Go to iv-luya.local/www/public_html and `run php index.php import`

or maybe run `vendor/bin/luya import` but i am not used to windows.

**Comment by igorveremsky** [comment]
`run php index.php import` works, but `vendor/bin/luya import` no. also thanks now i see my new layout in admin panel. i think issue can be closed.

**Comment by nadar** [comment]
Maybe there is also another solution to run the composer vendor bin files on windows.
