### ISSUE TITLE
after creating new page i cant edit it

### ISSUE THREAD

**Issue by igorveremsky** [luyadev/luya-kickstarter#21]
![screenshot_156](https://user-images.githubusercontent.com/13087365/36797634-199543ec-1cb1-11e8-8483-c6b7da7b3a27.png)

**Comment by nadar** [comment]
What happens if you click on "New Page" in the menu? Do you get a console error? Maybe check your console drawer.

Cause this looks good to me.

**Comment by igorveremsky** [comment]
my cursor change to red block icon, and when i click on "New Page" nothing happened. console screenshot after click

![screenshot_157](https://user-images.githubusercontent.com/13087365/36798461-608c0c98-1cb3-11e8-855b-4528dd649b8b.png)

**Comment by nadar** [comment]
Well then you have to grant yourself permissions in the cms permission view

**Comment by nadar** [comment]
@igorveremsky 

1. go to permissions of your groups and enable all permissions
<img width="1725" alt="bildschirmfoto 2018-02-28 um 17 42 39" src="https://user-images.githubusercontent.com/3417221/36800024-cecda91e-1cae-11e8-9442-a8e9f7f20f48.png">

2. go to page permissions and enable all for your groups:
<img width="700" alt="bildschirmfoto 2018-02-28 um 17 42 16" src="https://user-images.githubusercontent.com/3417221/36800000-c0b32548-1cae-11e8-9679-d6e20523fec1.png">

**Comment by igorveremsky** [comment]
i do 1 stage because it was at installation guide. now i done 2 stage and now all works fine, thanks!

**Comment by nadar** [comment]
The cms page permissions are also enabled by default, maybe you where trying something. Glad it works.
