### ISSUE TITLE
Exception on "php index.php import", "Setting unknown property: luya\admin\ngrest\plugins\Text::sortField"

### ISSUE THREAD

**Issue by diego-mathis** [luyadev/luya-kickstarter#41]
### What steps will reproduce the problem?
Just follow the guide: https://luya.io/guide/install-windows
Once import should be done:
> E:\yii2\luya-kickstarter\public_html>php index.php import

### What is the expected result?
Success

### What do you get instead? (A Screenshot can help us a lot!)

> Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: luya\admin\ngrest\plugins\Text::sortField'
> 
> in E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\Component.php:209
> 
> Stack trace:
> #0 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\BaseYii.php(546): yii\base\Component->__set('sortField', false)
> #1 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\BaseObject.php(107): yii\BaseYii::configure(Object(luya\admin\ngrest\plugins\Text), Array)
> #2 [internal function]: yii\base\BaseObject->__construct(Array)
> #3 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\di\Container.php(384): ReflectionClass->newInstanceArgs(Array)
> #4 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('\\luya\\admin\\ngr...', Array, Array)
> #5 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('\\luya\\admin\\ngr...', Array, Array)
> #6 E:\yii2\luya-kickstarter\vendor\luyadev\luya-module-admin\src\ngrest\NgRest.php(79): yii\BaseYii::createObject(Array)
> #7 E:\yii2\luya-kickstarter\vendor\luyadev\luya-module-admin\src\ngrest\base\NgRestEventBehavior.php(60): luya\admin\ngrest\NgRest::createPluginObject('\\luya\\admin\\ngr...', 'translationName', 'Name', false, Array)
> #8 E:\yii2\luya-kickstarter\vendor\luyadev\luya-module-admin\src\ngrest\base\NgRestEventBehavior.php(42): luya\admin\ngrest\base\NgRestEventBehavior::findPluginInstance('translationName', Array, 'cms_block')
> #9 [internal function]: luya\admin\ngrest\base\NgRestEventBehavior->bindPluginEvents(Object(yii\base\Event))
> #10 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\Component.php(627): call_user_func(Array, Object(yii\base\Event))
> #11 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\db\BaseActiveRecord.php(933): yii\base\Component->trigger('init')
> #12 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\db\BaseActiveRecord->init()
> #13 E:\yii2\luya-kickstarter\vendor\luyadev\luya-module-cms\src\admin\importers\BlockImporter.php(200): yii\base\BaseObject->__construct()
> #14 E:\yii2\luya-kickstarter\vendor\luyadev\luya-module-cms\src\admin\importers\BlockImporter.php(40): luya\cms\admin\importers\BlockImporter->saveBlock('\\luya\\cms\\front...')
> #15 E:\yii2\luya-kickstarter\vendor\luyadev\luya-core\console\commands\ImportController.php(177): luya\cms\admin\importers\BlockImporter->run()
> #16 [internal function]: luya\console\commands\ImportController->actionIndex()
> #17 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
> #18 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
> #19 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\console\Controller.php(148): yii\base\Controller->runAction('', Array)
> #20 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\Module.php(528): yii\console\Controller->runAction('', Array)
> #21 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('import', Array)
> #22 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('import', Array)
> #23 E:\yii2\luya-kickstarter\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
> #24 E:\yii2\luya-kickstarter\vendor\luyadev\luya-core\base\Boot.php(250): yii\base\Application->run()
> #25 E:\yii2\luya-kickstarter\vendor\luyadev\luya-core\base\Boot.php(205): luya\base\Boot->applicationConsole()
> #26 E:\yii2\luya-kickstarter\public_html\index.php(8): luya\base\Boot->run()
> #27 {main}
> 

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
E:\yii2\luya-kickstarter\public_html>php luyacheck.php
Did not work as I am not running Apache on my development machine.

> Fatal error: Uncaught Error: Call to undefined function apache_get_modules() in E:\yii2\luya-kickstarter\public_html\luyacheck.php(22) : eval()'d code:1
> Stack trace:
> #0 E:\yii2\luya-kickstarter\public_html\luyacheck.php(22): eval()
> #1 {main}
>   thrown in E:\yii2\luya-kickstarter\public_html\luyacheck.php(22) : eval()'d code on line 1

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |   1.0.18 (27. May 2019)
| PHP Version      | PHP 7.2.4 (cli) (built: Mar 28 2018 04:27:01) ( ZTS MSVC15 (Visual C++ 2017) x64 )
| Platform         | None
| Operating system | Windows 10 
|DB | MariaDB

**Comment by nadar** [comment]
What does your composer.json look like?

**Comment by nadar** [comment]
Hey @My6UoT9, yes indeed we made a mistake while taging latest LUYA cms patch release. Please try install the kickstarter again and let me know if it works.

**Comment by nadar** [comment]
I am going to close this issue, as its it was a problem with luya cms tag and not using admin 2.0 version.
