### ISSUE TITLE
questions about project and installation

### ISSUE THREAD

**Issue by GaneshKandu** [luyadev/luya-kickstarter#42]
Hi,

- is LUYA Open Source ? Under what license LUYA is released ?
- What are minimum PHP and mysql version required to install LUYA ?
- What PHP extensions are required to install LUYA ?

**Comment by nadar** [comment]
Hi @GaneshKandu 

+ Yes it is of course (https://github.com/luyadev/luya which is the core and required for admin and cms module) - MIT is the license
+ We recommend php 7.1 and also recommend mysql 5.7 but it should work with lower versions
+ https://luya.io/guide/install-problems section *Server requirements*

**Comment by GaneshKandu** [comment]
@nadar  Thanks !
