### ISSUE TITLE
Unable to create new version of a page in kickstarter

### ISSUE THREAD

**Issue by grrinch** [luyadev/luya-kickstarter#50]
### What steps will reproduce the problem?
composer create-project luyadev/luya-kickstarter
Go to admin -> Pages -> Homepage -> Add new version

Unable to add a new version with below information:
`One or more fields are empty or have an invalid value.`

### What is the expected result?
This is what I get when I go with 
`composer create-project luyadev/luya-kickstarter-bootstrap4`

![image](https://user-images.githubusercontent.com/5729796/97347271-74d81500-1884-11eb-941e-9d00e9ed0ca7.png)

### What do you get instead? (A Screenshot can help us a lot!)
![image](https://user-images.githubusercontent.com/5729796/97347287-7bff2300-1884-11eb-83b0-302f9a23d95d.png)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] ''
3: [ini_get('error_reporting')] '22527'
4: [phpversion()] '7.4.10'
5: [php_ini_loaded_file()] 'C:\\xampp\\php\\php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.10'

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 1.0.26
| PHP Version      | 7.4.10
| Platform         | XAMPP
| Operating system | Windows

**Comment by grrinch** [comment]
I also don't have these options when editing a page (as seen in your video):
![image](https://user-images.githubusercontent.com/5729796/97348029-8110a200-1885-11eb-9258-f0a7b7d231d0.png)

But I can live without them, so not that urgent. It would just be super-nice if someone explained why they're missing.

**Comment by grrinch** [comment]
ok, stupid me ... this solved the problem:

```
"require": {
        "luyadev/luya-core" : "^1.0",
        "luyadev/luya-module-admin" : "^3.0",
        "luyadev/luya-module-cms" : "^3.0",
        "luyadev/luya-bootstrap3" : "^1.0",
        "luyadev/luya-generic" : "^1.0"
    }
```

**Comment by nadar** [comment]
Hey @grrinch, did the composer update also fixed the problem when creating a new version? So you had an old version of admin and cms, right?

**Comment by grrinch** [comment]
Yes, it fixed both things. That's right.
